---
title: "git_01"
author: "Nicolas Rizo"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

The sun was shining on the sea,    
Shining with all his might:    
He did his very best to make    
The billows smooth and bright--    
And this was odd, because it was 

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

Two roads diverged in a yellow wood,  
And sorry I could not travel both  
And be one traveler, long I stood  
And looked down one as far as I could  
To where it bent in the undergrowth;  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

The sun was shining on the sea,  
 Shining with all his might:  
He did his very best to make  
 The billows smooth and bright —  
And this was odd, because it was  
 The middle of the night.  

The moon was shining sulkily,  
 Because she thought the sun  
 After the day was done —  
 “It’s very rude of him,” she said,  
“To come and spoil the fun.”  


## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

Out of the night that covers me,  
 Black as the pit from pole to pole,  
 I thank whatever gods may be  
 For my unconquerable soul.  

In the fell clutch of circumstance  
 I have not winced nor cried aloud.  
 Under the bludgeonings of chance My head is bloody, but unbowed.  

Beyond this place of wrath and tears  
 Looms but the Horror of the shade,  
 And yet the menace of the years  
 Finds and shall find me unafraid.  

It matters not how strait the gate,  
 How charged with punishments the scroll,  
 I am the master of my fate,  
 I am the captain of my soul.  

